/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inlamningsuppgifter;

//bara ändra EN sak när man debuggar


/**
 *
 * @author Emma.nilsson.567
 */
public class miniraknare_JFrame extends javax.swing.JFrame {
    String taldisplay;  //medlemsvariabel txfTaldisplay
        
    double tal1;
    double tal2;
    
    double result;
    
    String operations;     
    
    double minne = 0;
    
    int resultInt;
    
    int fakultet;
    
    /**
     * Creates new form miniraknare_JFrame
     */
    public miniraknare_JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnMultiplikation = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnSubtraktion = new javax.swing.JButton();
        btnAddition = new javax.swing.JButton();
        txfTaldisplay = new javax.swing.JTextField();
        btnBerakna = new javax.swing.JButton();
        btnDecimaltecken = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPositivtNegativt = new javax.swing.JButton();
        btnMinneLaggTill = new javax.swing.JButton();
        btnMinneSubtraheraDetta = new javax.swing.JButton();
        btnMemoryClear = new javax.swing.JButton();
        btnMemoryRecall = new javax.swing.JButton();
        btnRotenUrTalPaDisplay = new javax.swing.JButton();
        btnTaletKvarderasMed2 = new javax.swing.JButton();
        btnTalIKubik = new javax.swing.JButton();
        btnEttDelatMedTalet = new javax.swing.JButton();
        btnNFakultet = new javax.swing.JButton();
        btnxUpphöjtMedy = new javax.swing.JButton();
        lblMinne = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnMultiplikation.setText("*");
        btnMultiplikation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplikationActionPerformed(evt);
            }
        });

        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnSubtraktion.setText("-");
        btnSubtraktion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtraktionActionPerformed(evt);
            }
        });

        btnAddition.setText("+");
        btnAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdditionActionPerformed(evt);
            }
        });

        txfTaldisplay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txfTaldisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfTaldisplay.setToolTipText("");
        txfTaldisplay.setActionCommand("<Not Set>");
        txfTaldisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfTaldisplayActionPerformed(evt);
            }
        });

        btnBerakna.setText("=");
        btnBerakna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeraknaActionPerformed(evt);
            }
        });

        btnDecimaltecken.setText(".");
        btnDecimaltecken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalteckenActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnPositivtNegativt.setText("+/-");
        btnPositivtNegativt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPositivtNegativtActionPerformed(evt);
            }
        });

        btnMinneLaggTill.setText("M+");
        btnMinneLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinneLaggTillActionPerformed(evt);
            }
        });

        btnMinneSubtraheraDetta.setText("M-");
        btnMinneSubtraheraDetta.setActionCommand("");
        btnMinneSubtraheraDetta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinneSubtraheraDettaActionPerformed(evt);
            }
        });

        btnMemoryClear.setText("MC");
        btnMemoryClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryClearActionPerformed(evt);
            }
        });

        btnMemoryRecall.setText("MR");
        btnMemoryRecall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryRecallActionPerformed(evt);
            }
        });

        btnRotenUrTalPaDisplay.setText("√");
        btnRotenUrTalPaDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotenUrTalPaDisplayActionPerformed(evt);
            }
        });

        btnTaletKvarderasMed2.setText("X^2");
        btnTaletKvarderasMed2.setToolTipText("");
        btnTaletKvarderasMed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaletKvarderasMed2ActionPerformed(evt);
            }
        });

        btnTalIKubik.setText("X^3");
        btnTalIKubik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTalIKubikActionPerformed(evt);
            }
        });

        btnEttDelatMedTalet.setText("1/X");
        btnEttDelatMedTalet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEttDelatMedTaletActionPerformed(evt);
            }
        });

        btnNFakultet.setText("n!");
        btnNFakultet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNFakultetActionPerformed(evt);
            }
        });

        btnxUpphöjtMedy.setText("x^y");
        btnxUpphöjtMedy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxUpphöjtMedyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnRotenUrTalPaDisplay))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMultiplikation, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnSubtraktion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(btnDecimaltecken, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnBerakna, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnMemoryRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTaletKvarderasMed2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(btnMemoryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnMinneSubtraheraDetta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnMinneLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnPositivtNegativt)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnNFakultet, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnTalIKubik, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEttDelatMedTalet, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(btnxUpphöjtMedy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txfTaldisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblMinne, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txfTaldisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(lblMinne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTaletKvarderasMed2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTalIKubik, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEttDelatMedTalet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDecimaltecken, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRotenUrTalPaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMultiplikation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMemoryRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinneLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinneSubtraheraDetta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubtraktion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMemoryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnxUpphöjtMedy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBerakna, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPositivtNegativt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNFakultet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfTaldisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfTaldisplayActionPerformed
        // TODO add your handling code here:
//visa alla tal, ha metod stack för inmatning
taldisplay = txfTaldisplay.getText(); //taldisplay är det som står i txfTaldisplay

    }//GEN-LAST:event_txfTaldisplayActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
    String enternumber =txfTaldisplay.getText()+btn7.getText();
        
        txfTaldisplay.setText(enternumber); 
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
    String enternumber =txfTaldisplay.getText()+btn8.getText();
        
        txfTaldisplay.setText(enternumber); 
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
    String enternumber =txfTaldisplay.getText()+btn9.getText();
        
        txfTaldisplay.setText(enternumber);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnMultiplikationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplikationActionPerformed

SeOmAnvandarenSkrivitInEttTal ();    
try {
//försök hitta double    
tal1  =Double.valueOf(txfTaldisplay.getText()); 

}
catch (java.lang.NumberFormatException error){
//avbryter beräkningen
return;      
}

txfTaldisplay.setText("");
operations = "*";  

    }//GEN-LAST:event_btnMultiplikationActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
    String enternumber =txfTaldisplay.getText()+btn4.getText();
        
        txfTaldisplay.setText(enternumber);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
    String enternumber =txfTaldisplay.getText()+btn5.getText();
        
        txfTaldisplay.setText(enternumber);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
    String enternumber =txfTaldisplay.getText()+btn6.getText();
        
        txfTaldisplay.setText(enternumber);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed

SeOmAnvandarenSkrivitInEttTal ();    

try {
tal1  =Double.valueOf(txfTaldisplay.getText()); 
}
catch (java.lang.NumberFormatException error){
//avbryter beräkningen
return;      
}

txfTaldisplay.setText("");
operations="/";  

    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
    String enternumber =txfTaldisplay.getText()+btn3.getText();
        
        txfTaldisplay.setText(enternumber);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
    String enternumber =txfTaldisplay.getText()+btn2.getText();
        
        txfTaldisplay.setText(enternumber);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
    String enternumber =txfTaldisplay.getText()+btn1.getText();
        
        txfTaldisplay.setText(enternumber);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdditionActionPerformed
    // vid debugging kolla vad för tecken som kommer i min output. System.out.println("+");
        
SeOmAnvandarenSkrivitInEttTal ();    

try {
//försök hitta double    
tal1  =Double.valueOf(txfTaldisplay.getText()); 

}
catch (java.lang.NumberFormatException error){
return;  //avbryter beräkningen    
}
        

txfTaldisplay.setText("");
operations="+";        

    }//GEN-LAST:event_btnAdditionActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        
        txfTaldisplay.setText(""); 

//man kan använda och visa decimaltal
// BARA kunna skriva in en styck decimal

    }//GEN-LAST:event_btnCActionPerformed

    private void btnSubtraktionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtraktionActionPerformed

SeOmAnvandarenSkrivitInEttTal ();    

try {
//försök hitta double    
tal1  =Double.valueOf(txfTaldisplay.getText()); 

}
catch (java.lang.NumberFormatException error){
//avbryter beräkningen
return;      
}

        
txfTaldisplay.setText("");
operations="-";   

    }//GEN-LAST:event_btnSubtraktionActionPerformed

    private void btnBeraknaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeraknaActionPerformed

SeOmAnvandarenSkrivitInEttTal ();   

try {
        
//tal 1 finns som medlemsvariabel, heter double tal1

//tal 2 deklareras och tilldelas värde

tal2 = Double.valueOf(txfTaldisplay.getText());

    if (operations == "+"){
    result = tal1 + tal2; 
            if (result % 1 == 0){
            resultInt = (int)result;
            txfTaldisplay.setText(Integer.toString(resultInt));
            }
            else {
             //inget görs, kvar som double
                 txfTaldisplay.setText(Double.toString(result));
            }
    }
 
    
    else if (operations == "*"){  
    result = tal1 * tal2; 
            if (result % 1 == 0){
            resultInt = (int)result;
            txfTaldisplay.setText(Integer.toString(resultInt));
            }
            else {
            txfTaldisplay.setText(Double.toString(result));
            }
    }//GEN-LAST:event_btnBeraknaActionPerformed
    
    else if(operations == "-"){
    result = tal1 - tal2; 
            if (result % 1 == 0){
            resultInt = (int)result;
            txfTaldisplay.setText(Integer.toString(resultInt));
            }
            else {
                 txfTaldisplay.setText(Double.toString(result));
            }
    }
    
  else if (operations == "/"){
        
if(tal2 == 0){
txfTaldisplay.setText("Du kan inte dela med 0");
}        
else {
result = tal1 / tal2; 
            if (result % 1 == 0){
            resultInt = (int)result;
            txfTaldisplay.setText(Integer.toString(resultInt));
            }
            else {
                 txfTaldisplay.setText(Double.toString(result));
            }
    }
  }   
    
//tal1 är det tal som mulipleras med sig själv enligt det antal gånger som tal2 anger.
//ex 5^4 = 5*5*5*5.
    
    else if (operations == "^"){
        
    double xUpphojtMedY = Math.pow(tal1,tal2);
 

    txfTaldisplay.setText(Double.toString(xUpphojtMedY));
        }
        
    }
catch (java.lang.NumberFormatException error){
return;     //avbryter beräkningen
}
 
}
    
    
    private void btnDecimalteckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalteckenActionPerformed
//villkora att bara ett , får finnas i txfTaldisplay
//Nu har jag gjort så att knappen inte fungerar om . redan finns.
        
String display = txfTaldisplay.getText();
        
//letar efter . Returnerar vilken indexplats . finns på. Ger -1 om . inte finns. s.35.
int index = display.indexOf('.');

//om strängen INTE innehåller ett decimaltecken
if (index < 0 ){
txfTaldisplay.setText(display + ("."));
    }
    
    
    }//GEN-LAST:event_btnDecimalteckenActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
    String enternumber =txfTaldisplay.getText()+btn0.getText();
        
    txfTaldisplay.setText(enternumber);    
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPositivtNegativtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPositivtNegativtActionPerformed

SeOmAnvandarenSkrivitInEttTal ();    

try {
//försök hitta double    
double andraSiffranFore = Double.valueOf(txfTaldisplay.getText()) * (-1);


    if (andraSiffranFore % 1 == 0){
    resultInt = (int)andraSiffranFore;
    txfTaldisplay.setText(Integer.toString(resultInt));
        }
    else {
    //inget görs, kvar som double
    txfTaldisplay.setText(String.valueOf(andraSiffranFore));
          }
}
catch (java.lang.NumberFormatException error){
return;     //avbryter beräkningen
}

    }//GEN-LAST:event_btnPositivtNegativtActionPerformed

    private void btnMinneLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinneLaggTillActionPerformed
    
    SeOmAnvandarenSkrivitInEttTal (); 
        
try {
    
//double (från display string)
double tillMinne = Double.valueOf(txfTaldisplay.getText());
         
minne = minne + tillMinne;

visaSymbolOmDetFinnsVardeIMinnet(); 
    
}
catch (java.lang.NumberFormatException error){
return;     //avbryter beräkningen
}
    }//GEN-LAST:event_btnMinneLaggTillActionPerformed

    private void btnMinneSubtraheraDettaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinneSubtraheraDettaActionPerformed
           
SeOmAnvandarenSkrivitInEttTal ();    
//tal på displayen hämtas
try {   
                
double subtraheraDetta = Double.valueOf(txfTaldisplay.getText());
         
    minne = minne - subtraheraDetta;
    
visaSymbolOmDetFinnsVardeIMinnet();
}

catch (java.lang.NumberFormatException error){
return;     //avbryter beräkningen
}

    }//GEN-LAST:event_btnMinneSubtraheraDettaActionPerformed

    private void btnMemoryClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryClearActionPerformed
   
    minne = 0;
    
visaSymbolOmDetFinnsVardeIMinnet();
        
    }//GEN-LAST:event_btnMemoryClearActionPerformed

    private void btnMemoryRecallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryRecallActionPerformed
        
 if (minne % 1 == 0){
            int Iminne = (int)minne;
                txfTaldisplay.setText(Integer.toString(Iminne));
            }
            else {
         txfTaldisplay.setText(Double.toString(minne));
            }                       
                        
    }//GEN-LAST:event_btnMemoryRecallActionPerformed

    private void btnRotenUrTalPaDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotenUrTalPaDisplayActionPerformed
        // Roten ur det det som står på taldisplayen //BtnRotenUr case * tfxTaldisplay.

Double rotenUr;        
        
SeOmAnvandarenSkrivitInEttTal ();  

try {
//försök hitta double    
rotenUr = Double.valueOf(txfTaldisplay.getText());
}
catch (java.lang.NumberFormatException error){

return;    //avbryter beräkningen  
}

if(rotenUr < 0){
txfTaldisplay.setText("talet måste vara ett positivt tal."); //felmeddelande ges
}        
        //om talet är större än 0.
    double roten = Math.sqrt(rotenUr) ;
    
       if (roten % 1 == 0){
            int introten = (int)roten;
                txfTaldisplay.setText(Integer.toString(introten));
            }    
         
        else {
        txfTaldisplay.setText(Double.toString(roten));
            } 
    
               
 
    }//GEN-LAST:event_btnRotenUrTalPaDisplayActionPerformed

    private void btnTaletKvarderasMed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaletKvarderasMed2ActionPerformed
SeOmAnvandarenSkrivitInEttTal ();    


try {
String kvaderaras2String = txfTaldisplay.getText();

double kvadrera2 = Double.valueOf(kvaderaras2String) * Double.valueOf(kvaderaras2String);        
        
if (kvadrera2 % 1 == 0){
            resultInt = (int)kvadrera2;
            txfTaldisplay.setText(Integer.toString(resultInt));
            }
            else {
    txfTaldisplay.setText(Double.toString(kvadrera2));        
            }           
}


catch (java.lang.NumberFormatException error){
return;    //avbryter 
}
 

    }//GEN-LAST:event_btnTaletKvarderasMed2ActionPerformed

    private void btnTalIKubikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTalIKubikActionPerformed
        // talet upphöjt med 3 / talIKubik

SeOmAnvandarenSkrivitInEttTal ();    

try {
String talIKubikString = txfTaldisplay.getText();
        
    double talIKubik = Double.valueOf(talIKubikString) * 
            Double.valueOf(talIKubikString) * Double.valueOf(talIKubikString);        
        
if (talIKubik % 1 == 0){
            resultInt = (int)talIKubik;
            txfTaldisplay.setText(Integer.toString(resultInt));
            }
            else {
    txfTaldisplay.setText(Double.toString(talIKubik));  
             }      
}
catch (java.lang.NumberFormatException error){
return;     //avbryter beräkningen
}

    }//GEN-LAST:event_btnTalIKubikActionPerformed

    private void btnEttDelatMedTaletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEttDelatMedTaletActionPerformed
        // 1 (täljare) delat på tal (nämnare) i display
        
SeOmAnvandarenSkrivitInEttTal ();    

try {        
    String namnare = txfTaldisplay.getText();
        
    double resultatet = 1/Double.valueOf(namnare);        
        
    if (resultatet % 1 == 0){
            resultInt = (int)resultatet;
            txfTaldisplay.setText(Integer.toString(resultInt));
            }
            else {
            txfTaldisplay.setText(Double.toString(resultatet));    
            }
}
catch (java.lang.NumberFormatException error){
return;     //avbryter beräkningen
}


    }//GEN-LAST:event_btnEttDelatMedTaletActionPerformed

    private void btnNFakultetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNFakultetActionPerformed
//n! ska bara fungera för positiva heltal. (loop ”uppräkning” sen multiplicera talen).
//n! (utläses "n fakultet" och beräknas tex 5!=1*2*3*4*5=120). Utropstecknet betyder fackultet.

SeOmAnvandarenSkrivitInEttTal ();    

try {
//konverteras till double (men hämtades som String).
double fakultetSomDecimal = Double.valueOf(txfTaldisplay.getText());
    
//talet är ett heltal OCH större än 0
if ((fakultetSomDecimal % 1 == 0) && fakultetSomDecimal > 0 ){
        
    //konverteras till int. (som är medlemsvariabel.)
    fakultet = (int)fakultetSomDecimal; 

    int summa =1;

    for (int i=1 ; i <= fakultet ; i++){ //start 1 ;slut 5 ; i++ 
    summa*= i;  //1*1= 1, 1*2 = 2, 2*3 = 6, 6*4 = 24, 24 * 5 = 120
        System.out.println(summa + " ");
    }
    
    
    txfTaldisplay.setText(Integer.toString(summa));     
    }

else {
    txfTaldisplay.setText("talet måste vara ett positivt heltal."); //felmeddelande ges
}

}   

catch (java.lang.NumberFormatException error){
return;     //avbryter beräkningen
}


    }//GEN-LAST:event_btnNFakultetActionPerformed

    private void btnxUpphöjtMedyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxUpphöjtMedyActionPerformed
//hämtar texten och gör om den från string till double. 
SeOmAnvandarenSkrivitInEttTal ();    

try {
tal1  =Double.valueOf(txfTaldisplay.getText()); 
}
catch (java.lang.NumberFormatException error){
return;     //avbryter beräkningen
}

txfTaldisplay.setText("");
operations="^"; 


    }//GEN-LAST:event_btnxUpphöjtMedyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(miniraknare_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(miniraknare_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(miniraknare_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(miniraknare_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miniraknare_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAddition;
    private javax.swing.JButton btnBerakna;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnDecimaltecken;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnEttDelatMedTalet;
    private javax.swing.JButton btnMemoryClear;
    private javax.swing.JButton btnMemoryRecall;
    private javax.swing.JButton btnMinneLaggTill;
    private javax.swing.JButton btnMinneSubtraheraDetta;
    private javax.swing.JButton btnMultiplikation;
    private javax.swing.JButton btnNFakultet;
    private javax.swing.JButton btnPositivtNegativt;
    private javax.swing.JButton btnRotenUrTalPaDisplay;
    private javax.swing.JButton btnSubtraktion;
    private javax.swing.JButton btnTalIKubik;
    private javax.swing.JButton btnTaletKvarderasMed2;
    private javax.swing.JButton btnxUpphöjtMedy;
    private javax.swing.JLabel lblMinne;
    private javax.swing.JTextField txfTaldisplay;
    // End of variables declaration//GEN-END:variables

private void visaSymbolOmDetFinnsVardeIMinnet(){
 
     if (minne > 0 || minne <0){
        lblMinne.setText("M");    
        }
     else{
        lblMinne.setText("");             
     }
}

private void SeOmAnvandarenSkrivitInEttTal (){
    String display = txfTaldisplay.getText();
        
  if (display.isBlank()){
   txfTaldisplay.setText("Skriv in ett tal först.");    
   }
  
}


}
